# Generated by Django 4.1.3 on 2023-01-17 01:38

import admincontrol.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("current_position", models.CharField(max_length=100)),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("superadmin", "SUPERADMIN"),
                            ("admin", "ADMIN"),
                            ("user", "USER"),
                        ],
                        default=admincontrol.models.PowerShare["USER"],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
