# Generated by Django 4.1.3 on 2023-01-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admincontrol", "0003_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="current_position",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
