# Generated by Django 4.1.3 on 2023-01-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admincontrol", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fullname",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
