# Generated by Django 4.1.3 on 2023-01-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admincontrol", "0002_user_fullname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(default="true", max_length=100),
        ),
    ]
