# Generated by Django 4.1.3 on 2023-01-17 01:38

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_asset", models.CharField(max_length=100)),
                ("supporting_gear", models.CharField(blank=True, max_length=100)),
                ("quantity", models.IntegerField()),
                ("date_of_purchase", models.DateField()),
                ("rate_per_unit", models.FloatField(max_length=100)),
                (
                    "condition_of_asset",
                    models.CharField(
                        choices=[
                            ("New", "NEW"),
                            ("Good", "GOOD"),
                            ("Not usable", "UNUSABLE"),
                            ("Requires Repairment", "REQUIREREPAIR"),
                            ("Lost", "LOST"),
                        ],
                        default=products.models.Condition["GOOD"],
                        max_length=50,
                    ),
                ),
                (
                    "assets_pool",
                    models.CharField(
                        choices=[
                            (
                                "Building, structure and similar other structures of permanent nature.",
                                "A",
                            ),
                            (
                                "Computer, data processing equipment, furniture, fixture and office equipment.",
                                "B",
                            ),
                            ("Automobiles, buses and mini-buses.", "C"),
                            (
                                "Construction and excavation equipment, and the depreciable properties not included in elsewhere including Sub-section (3) of Section 17, Sub-section (3) of Section 18, and Sub-section (3) of this Schedule.",
                                "D",
                            ),
                            (
                                "Intangible properties except the depreciable properties mentioned in category 'D'.",
                                "E",
                            ),
                        ],
                        default=products.models.AssetPool["A"],
                        max_length=500,
                    ),
                ),
                (
                    "asset_location",
                    models.CharField(
                        choices=[
                            ("Department A (room 1)", "DEPARTMENT_A"),
                            ("room 4", "KITCHEN"),
                            ("room 5", "STORE_1"),
                            ("Garrage", "GARRAGE"),
                            ("office premises", "OFFICE_PREMISES"),
                            ("gandaki office", "GANDAKI_OFFICE"),
                        ],
                        default=products.models.AssetLocation["OFFICE_PREMISES"],
                        max_length=50,
                    ),
                ),
                ("image_1", models.ImageField(blank=True, upload_to="media/product/")),
                ("image_2", models.ImageField(blank=True, upload_to="media/product/")),
                ("image_3", models.ImageField(blank=True, upload_to="media/product/")),
                ("purpose_of_asset", models.CharField(max_length=500)),
                ("date_of_update", models.DateField()),
                ("product_category", models.CharField(max_length=200)),
                ("vendor", models.CharField(max_length=200)),
                ("user", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_no", models.CharField(max_length=100)),
                ("name_of_vendor", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=100)),
                ("contact_person", models.CharField(max_length=500)),
                ("contact_no", models.IntegerField()),
                ("pan_no", models.IntegerField()),
            ],
        ),
    ]
