# Generated by Django 4.1.3 on 2023-01-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_vendor_vat_no_alter_vendor_pan_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="asset_code",
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_no",
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
