# Generated by Django 4.1.3 on 2023-01-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_product_asset_code_alter_vendor_vendor_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="vendor_no",
            field=models.CharField(
                blank=True, default=None, max_length=100, unique=True
            ),
        ),
    ]
