# Generated by Django 4.1.3 on 2023-01-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_product_asset_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="asset_code",
            field=models.CharField(
                default=None, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_no",
            field=models.CharField(
                default=None, max_length=100, null=True, unique=True
            ),
        ),
    ]
