# Generated by Django 4.1.3 on 2023-01-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_product_asset_code_alter_vendor_vendor_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="asset_location",
            field=models.CharField(
                choices=[
                    ("Department A (room 1)", "DEPARTMENT_A"),
                    ("room 4", "KITCHEN"),
                    ("room 5", "STORE_1"),
                    ("Garrage", "GARRAGE"),
                    ("office premises", "OFFICE_PREMISES"),
                    ("gandaki office", "GANDAKI_OFFICE"),
                ],
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="assets_pool",
            field=models.CharField(
                choices=[
                    (
                        "Building, structure and similar other structures of permanent nature.",
                        "A",
                    ),
                    (
                        "Computer, data processing equipment, furniture, fixture and office equipment.",
                        "B",
                    ),
                    ("Automobiles, buses and mini-buses.", "C"),
                    (
                        "Construction and excavation equipment, and the depreciable properties not included in elsewhere including Sub-section (3) of Section 17, Sub-section (3) of Section 18, and Sub-section (3) of this Schedule.",
                        "D",
                    ),
                    (
                        "Intangible properties except the depreciable properties mentioned in category 'D'.",
                        "E",
                    ),
                ],
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="condition_of_asset",
            field=models.CharField(
                choices=[
                    ("New", "NEW"),
                    ("Good", "GOOD"),
                    ("Not usable", "UNUSABLE"),
                    ("Requires Repairment", "REQUIREREPAIR"),
                    ("Lost", "LOST"),
                ],
                max_length=50,
            ),
        ),
    ]
