# Generated by Django 4.1.3 on 2023-01-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_product_asset_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="availale_status",
            field=models.CharField(default="true", max_length=10),
        ),
        migrations.AddField(
            model_name="vendor",
            name="status",
            field=models.CharField(default="true", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(default="true", max_length=10),
        ),
    ]
