# Generated by Django 4.1.3 on 2023-01-21 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_product_availale_status_vendor_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("Model_no", models.CharField(blank=True, max_length=100)),
                ("year_of_manufacture", models.CharField(blank=True, max_length=100)),
                ("color", models.CharField(blank=True, max_length=100)),
                ("size", models.CharField(blank=True, max_length=100)),
                ("warranty_period", models.CharField(blank=True, max_length=100)),
                ("other_specs", models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.specifications",
            ),
        ),
    ]
