# Generated by Django 4.1.3 on 2023-01-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admincontrol", "0003_user_status"),
        ("products", "0016_specifications_product_specifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="user",
        ),
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ManyToManyField(to="admincontrol.user"),
        ),
    ]
