# Generated by Django 4.1.3 on 2023-01-23 00:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admincontrol", "0003_user_status"),
        ("products", "0017_remove_product_user_product_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssestReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nameofstaffreturningasset", models.CharField(max_length=100)),
                ("asset_verified_by", models.CharField(max_length=100)),
                ("asset_issued_in", models.DateField()),
                (
                    "expected_date_of_return_of_such_asset",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "date_of_return",
                    models.DateField(blank=True, default=datetime.datetime.now),
                ),
                ("did_return_all", models.CharField(blank=True, max_length=50)),
                ("token", models.CharField(blank=True, max_length=100)),
                (
                    "asset_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "asset_release_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admincontrol.user",
                    ),
                ),
            ],
        ),
    ]
