# Generated by Django 4.1.3 on 2023-01-23 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_assestreturn_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_1",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image_2",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image_3",
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(upload_to="produt_image/")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
