# Generated by Django 4.1.3 on 2023-01-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_alter_product_date_of_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date_of_purchase",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="date_of_update",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
