# Generated by Django 4.1.3 on 2023-01-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0024_alter_product_specifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assestassign",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="assestreturn",
            name="quantity",
        ),
    ]
