# Generated by Django 4.1.3 on 2023-02-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0029_remove_assestreturn_asset_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assestreturn",
            name="asset_release_by",
            field=models.CharField(max_length=100),
        ),
    ]
