# Generated by Django 4.1.3 on 2023-02-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0033_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="status",
            field=models.CharField(default="true", max_length=100),
        ),
    ]
