# Generated by Django 4.1.3 on 2023-01-17 03:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssestAssign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nameofstaff", models.CharField(max_length=100)),
                ("purpose", models.CharField(max_length=300)),
                (
                    "date_of_issue",
                    models.DateField(blank=True, default=datetime.datetime.now),
                ),
                ("estimated_date_of_return", models.DateField()),
                ("asset_verified_by", models.CharField(max_length=100)),
                ("position_of_verified_authority", models.CharField(max_length=100)),
                (
                    "asset_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
