# Generated by Django 4.1.3 on 2023-01-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_assestassign"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(default="false", max_length=10),
        ),
    ]
