# Generated by Django 4.1.3 on 2023-01-19 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admincontrol", "0001_initial"),
        ("products", "0003_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assestassign",
            name="asset_verified_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="admincontrol.user"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="admincontrol.user"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.vendor"
            ),
        ),
    ]
