# Generated by Django 4.1.3 on 2023-01-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_assestassign_asset_verified_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assestassign",
            name="position_of_verified_authority",
        ),
    ]
