# Generated by Django 4.1.3 on 2023-01-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_assestassign_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="assestassign",
            name="quantity",
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
