# Generated by Django 4.1.3 on 2023-01-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_assestassign_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="vat_no",
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="pan_no",
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
