# Generated by Django 4.1.3 on 2023-01-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_vendor_vendor_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="asset_code",
            field=models.CharField(
                blank=True, default=None, max_length=100, unique=True
            ),
        ),
    ]
