# Generated by Django 4.1.3 on 2023-01-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_product_asset_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="asset_location",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="assets_pool",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="condition_of_asset",
            field=models.CharField(max_length=50),
        ),
    ]
