# Generated by Django 4.1.3 on 2023-01-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_remove_product_image_1_remove_product_image_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date_of_update",
            field=models.DateField(blank=True),
        ),
    ]
