# Generated by Django 4.1.3 on 2023-01-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admincontrol", "0004_alter_user_current_position"),
        ("products", "0025_remove_assestassign_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="user",
            field=models.ManyToManyField(blank=True, to="admincontrol.user"),
        ),
    ]
