# Generated by Django 4.1.3 on 2023-02-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0030_alter_assestreturn_asset_release_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assestreturn",
            name="expected_date_of_return_of_such_asset",
            field=models.DateField(),
        ),
    ]
